# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dea2588969d303dbcba904ffe5f686ccc66b2366d645bbe24387531c5e54bababef55e86285631ed1e4d532865ba60d39289e5b66abd2e067da84ed9c5d0bf3e

test:
  secret_key_base: e31c967cd8dafc317534307e85d7478e7ff279f91b4126804c6042dae22edbe1c1bc577c78070bd172c00342297edeba3baa1425543ad2edf7ad4bfa7ae1ebda

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
